server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://localhost3306/users?autoReconnect=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver

  redis:
    host: 127.0.0.1
    port: 6379


sms:
  code:
    timeout: 5

  token:
    timeout: 30
