server:
  port: 10001
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:file:./data/h2/dev
    platform: h2
    username: user
    password: user
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:db/init.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: 127.0.0.1
    port: 6379

auth:
  token:
    secretKey: sign-in-up-secret-key
    expireTime: 3600000


sms:
  code:
    timeout: 5

  token:
    timeout: 30
